"""
AutoML Studio — Auto Research Paper Generator (Feature #7)
Generates a structured technical report / research paper from experiment results.
"""

import datetime


def generate_paper(profile, clean_report, transform_report, training_results,
                    explainability=None, fairness=None, session_data=None):
    """
    Generate a full structured research paper from experiment data.

    Returns:
        dict with sections of the paper in markdown format
    """
    target = profile.get('target_column', 'target') if profile else 'target'
    problem_type = profile.get('problem_type', 'classification') if profile else 'classification'
    n_rows = profile.get('n_rows', 0) if profile else 0
    n_cols = profile.get('n_cols', 0) if profile else 0
    leaderboard = training_results.get('leaderboard', []) if training_results else []
    best_model = training_results.get('best_model', 'N/A') if training_results else 'N/A'
    best_score = training_results.get('best_score', 0) if training_results else 0
    metric = training_results.get('primary_metric_name', 'score') if training_results else 'score'

    now = datetime.datetime.now().strftime('%B %d, %Y')

    sections = {}

    # Title
    sections['title'] = f'Automated Machine Learning Analysis: {problem_type.title()} on {target}'
    sections['date'] = now
    sections['authors'] = 'Generated by AutoML Studio'

    # Abstract
    n_models = len(leaderboard)
    sections['abstract'] = (
        f'This study presents an automated machine learning analysis on a dataset '
        f'with {n_rows:,} samples and {n_cols} features. The objective is '
        f'{problem_type} prediction of the target variable "{target}". '
        f'A total of {n_models} models were trained and evaluated using cross-validation. '
        f'The best performing model, {best_model}, achieved a {metric} of {best_score:.4f}. '
        f'This report covers data preprocessing, feature engineering, model selection, '
        f'hyperparameter tuning, and model interpretation.'
    )

    # Introduction
    missing_pct = profile.get('total_missing_pct', 0) if profile else 0
    sections['introduction'] = (
        f'## 1. Introduction\n\n'
        f'The dataset contains {n_rows:,} observations and {n_cols} features. '
        f'The prediction task is **{problem_type}** with target variable `{target}`. '
        f'The dataset has {missing_pct:.1f}% missing values and '
        f'{profile.get("duplicates", 0)} duplicate rows. '
        f'{len(profile.get("numeric_columns", []))} features are numeric and '
        f'{len(profile.get("categorical_columns", []))} are categorical.'
    )

    # Methodology
    clean_steps = clean_report.get('steps', []) if clean_report else []
    transform_steps = transform_report.get('steps', []) if transform_report else []
    sections['methodology'] = (
        f'## 2. Methodology\n\n'
        f'### 2.1 Data Preprocessing\n'
        f'The following cleaning steps were applied:\n'
    )
    for step in clean_steps:
        if step.get('applied'):
            sections['methodology'] += f'- **{step["name"]}**: {step["description"]}\n'
    sections['methodology'] += (
        f'\n### 2.2 Feature Engineering\n'
        f'The following transformations were applied:\n'
    )
    for step in transform_steps:
        if step.get('applied'):
            sections['methodology'] += f'- **{step["name"]}**: {step["description"]}\n'
    sections['methodology'] += (
        f'\n### 2.3 Model Selection\n'
        f'{n_models} models were trained with 5-fold cross-validation. '
        f'Top 3 models were further tuned using Bayesian optimisation (Optuna).'
    )

    # Results
    sections['results'] = f'## 3. Results\n\n### 3.1 Model Leaderboard\n\n'
    sections['results'] += f'| Rank | Model | {metric.title()} |\n|------|-------|-------|\n'
    for entry in leaderboard[:10]:
        sections['results'] += f'| {entry["rank"]} | {entry["model"]} | {entry["primary_metric"]:.4f} |\n'

    # Feature importance
    fi = training_results.get('feature_importance', []) if training_results else []
    if fi:
        sections['results'] += '\n### 3.2 Feature Importance\n\n'
        sections['results'] += '| Feature | Importance |\n|---------|------------|\n'
        for f in fi[:10]:
            sections['results'] += f'| {f["feature"]} | {f["importance"]:.4f} |\n'

    # Discussion
    overfit_gap = 0
    if leaderboard:
        m = leaderboard[0].get('metrics', {})
        train_k = 'train_accuracy' if problem_type == 'classification' else 'train_r2'
        test_k = 'accuracy' if problem_type == 'classification' else 'r2'
        overfit_gap = m.get(train_k, 0) - m.get(test_k, 0)

    sections['discussion'] = (
        f'## 4. Discussion\n\n'
        f'The best model ({best_model}) achieved {metric}={best_score:.4f}. '
    )
    if overfit_gap > 0.1:
        sections['discussion'] += (
            f'An overfitting gap of {overfit_gap:.1%} was observed between training and test scores. '
            f'Additional regularisation or more training data may improve generalisation. '
        )
    else:
        sections['discussion'] += 'The model shows good generalisation with minimal overfitting. '

    # Limitations
    sections['limitations'] = (
        f'## 5. Limitations\n\n'
        f'- Results are based on a single train/test split (75/25)\n'
        f'- Hyperparameter search was limited to 20 trials per model\n'
        f'- Feature engineering was automated and may miss domain-specific transformations\n'
        f'- Model performance may degrade on data with different distributions\n'
    )

    # Conclusion
    sections['conclusion'] = (
        f'## 6. Conclusion\n\n'
        f'{best_model} is recommended for deployment with a {metric} of {best_score:.4f}. '
        f'The automated pipeline successfully handled data cleaning, feature engineering, '
        f'and model selection without manual intervention.'
    )

    # References
    sections['references'] = (
        f'## References\n\n'
        f'- Pedregosa et al. (2011). Scikit-learn: Machine Learning in Python. JMLR 12.\n'
        f'- Akiba et al. (2019). Optuna: A Next-gen Hyperparameter Optimization Framework.\n'
        f'- Lundberg & Lee (2017). A Unified Approach to Interpreting Model Predictions. NeurIPS.\n'
        f'- Chen & Guestrin (2016). XGBoost: A Scalable Tree Boosting System. KDD.\n'
    )

    # Full paper
    full = f'# {sections["title"]}\n\n'
    full += f'*{sections["authors"]} — {sections["date"]}*\n\n'
    full += f'## Abstract\n\n{sections["abstract"]}\n\n'
    full += sections['introduction'] + '\n\n'
    full += sections['methodology'] + '\n\n'
    full += sections['results'] + '\n\n'
    full += sections['discussion'] + '\n\n'
    full += sections['limitations'] + '\n\n'
    full += sections['conclusion'] + '\n\n'
    full += sections['references']

    return {
        'sections': sections,
        'full_paper_markdown': full,
        'word_count': len(full.split()),
        'format': 'markdown',
    }
